.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "QUBES\-REMOTE\-SUPPORT\-PROVIDER" "8" "January 2020" "qubes-whonix" "qubes-whonix Manual"
.SH "NAME"
\fBqubes\-remote\-support\-provider\fR \- Qubes Remote Support Provider
.SH "SYNOPSIS"
\fBqubes\-remote\-support\-provider\fR
.SH "DESCRIPTION"
Builds mediate time by asking three onion servers from three different pools\.
.SH "EXAMPLES"
\fBqubes\-remote\-support\-provider\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
