#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :
#
# enable-firewall - Called by systemd to setup a proper firewall for Whonix
#                   gateway, workstation or template
#
# This file is part of Qubes+Whonix.
# Copyright (C) 2014 - 2015 Jason Mehring <nrgaway@gmail.com>
# Copyright (C) 2014 - 2016 Patrick Schleizer <adrelanos@riseup.net>
# License: GPL-2+
# Authors: Jason Mehring
# Authors: Patrick Schleizer
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

[ -n "$iptables_cmd" ] || iptables_cmd="iptables --wait"
[ -n "$ip6tables_cmd" ] || ip6tables_cmd="ip6tables --wait"

qubes_vm_type="$(qubesdb-read /qubes-vm-type)"

# Template
if [ "$qubes_vm_type" = "TemplateVM" ]; then

    true

# Gateway or Workstation
elif [ -e /usr/share/anon-gw-base-files/gateway ] || [ -e /usr/share/anon-ws-base-files/workstation ]; then

    # Load the Whonix firewall
    /usr/bin/whonix_firewall || touch /var/run/qubes-service/whonix-firewall-failed

else
    touch /var/run/qubes-service/whonix-firewall-failed
fi

# Something is not right; lock down networking.  User will be notified
if [ -e /var/run/qubes-service/whonix-firewall-failed ]; then

    # Set secure defaults.
    $iptables_cmd -P INPUT DROP
    $iptables_cmd -P FORWARD DROP
    $iptables_cmd -P OUTPUT DROP

    # Flush old rules.
    $iptables_cmd -F
    $iptables_cmd -X
    $iptables_cmd -t nat -F
    $iptables_cmd -t nat -X
    $iptables_cmd -t mangle -F
    $iptables_cmd -t mangle -X
fi

exit 0
