#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :
#
# qubes-whonix-postinit - Called by systemd used to setup other required
#                         configurations before network is started.
#
# Copyright (C) 2014 - 2015 Jason Mehring <nrgaway@gmail.com>
# License: GPL-2+
# Authors: Jason Mehring
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -x

qubes_vm_type="$(qubesdb-read /qubes-vm-type)"

if [ "$qubes_vm_type" = "TemplateVM" ]; then
   # Do none of the following in a TemplateVM.
   exit 0
fi

# Replace IP addresses in known configuration files / scripts with
# currently discovered IP address
/usr/lib/qubes-whonix/replace-ips

if [ -e /usr/share/anon-gw-base-files/gateway ]; then

    tor_disable_file=/usr/local/etc/torrc.d/51_tor_disable.conf
    tor_enable_file=/usr/local/etc/torrc.d/49_tor_enable.conf

    # Enable/Disable Tor if qubes-service is enabled
    if [ -e /run/qubes-service/whonix-tor-enable ]; then
         rm -f "$tor_disable_file"
         echo "DisableNetwork 0" > "$tor_enable_file"

    elif [ -e /run/qubes-service/whonix-tor-disable ]; then
         rm -f "$tor_enable_file"
         echo "DisableNetwork 1" > "$tor_disable_file"
    fi

fi
