#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :
#
# qubes-whonix-sysinit - Called by systemd during the sysinit boot stage to
#                        initialize required configurations for Whonix
#
# This file is part of Qubes+Whonix.
# Copyright (C) 2014 - 2015 Jason Mehring <nrgaway@gmail.com>
# License: GPL-2+
# Authors: Jason Mehring
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

qubes_vm_type="$(qubesdb-read /qubes-vm-type)"

if [ "$qubes_vm_type" = "TemplateVM" ]; then
   # Do none of the following in a TemplateVM.
   exit 0
fi

# Trigger starting the systemd qubes-updates-proxy.service on gateways, unless
# already configured to trigger starting qubes-updates-cache.service instead.
# The caching one is heavier, hence the user is supposed to enable it manually
# with qvm-service or the Qubes VM Manager's Services tab. The same applies if
# the user wants to enable the non-caching proxy on workstations, so as not to
# waste 4 MB memory everywhere.
if [   -e /usr/share/anon-gw-base-files/gateway -a \
     ! -e /var/run/qubes-service/qubes-updates-cache ]; then
    touch /var/run/qubes-service/qubes-updates-proxy
fi
