#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :
#
# enable-firewall - Called by systemd to setup a proper firewall for Whonix
#                   gateway, workstation or template
#
# This file is part of Qubes+Whonix.
# Copyright (C) 2014 - 2015 Jason Mehring <nrgaway@gmail.com>
# License: GPL-2+
# Authors: Jason Mehring
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

qubes_vm_type="$(qubesdb-read /qubes-vm-type)"

if [ ! "$qubes_vm_type" = "TemplateVM" ]; then
   exit 0
fi

if [ -e /var/run/qubes-service/whonix-secure-proxy ]; then
   exit 0
fi

source /usr/lib/qubes-whonix/utility_functions.sh

## Check if a secure Tor update server is available
curl_output="$(UWT_DEV_PASSTHROUGH="1" curl --silent --connect-timeout 3 "${PROXY_SERVER}")" || true

if echo "$curl_output" | grep -q "${PROXY_META}" ; then
   touch /var/run/qubes-service/whonix-secure-proxy
fi
