#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :
#
# qubes-whonixsetup - Called by /etc/xdg/autostart/qubes-whonixsetup.desktop
#
# Performs various Whonix 'setup' related tasks which will notify or prompt the
# user if any required configurations need attention and also warn the user the
# VM is going to be powered off if a failure of one of the configurations was
# detected.
#
# This file is part of Qubes+Whonix.
# Copyright (C) 2014 - 2015 Jason Mehring <nrgaway@gmail.com>
# License: GPL-2+
# Authors: Jason Mehring
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

qubes_vm_type="$(qubesdb-read /qubes-vm-type)"

# Template
if [ "$qubes_vm_type" = "TemplateVM" ]; then

    # Display warning that TemplateVM is not connected to a Tor update proxy.
    if [ ! -e '/var/run/qubes-service/whonix-secure-proxy' ]; then
        /usr/lib/qubes-whonix/alert update /usr/lib/qubes-whonix/messages.yaml
    fi

# Gateway
elif [ -e /usr/share/anon-gw-base-files/gateway ]; then

    # If Tor is disabled, start whonix-setup-wizard in quick mode.
    if grep "^#DisableNetwork 0$" /etc/tor/torrc; then
        kdesudo whonix-setup-wizard quick
    fi

    # Display alert that 'whonix-tor-disable' service flag is set and it will need to
    # to manually unset if user wants to be able to boot with Tor enabled.
    if [ -e /var/run/qubes-service/whonix-tor-disable ]; then
        /usr/lib/qubes-whonix/alert tor-disabled /usr/lib/qubes-whonix/messages.yaml
        exit 0
    fi

    ## When whonixcheck is automatically started at boot, while Tor is disabled
    ## in /etc/tor/torrc, whonixcheck exits silently.
    ## (whonixcheck does this because it is assumed, that in these cases Whonix
    ## Setup starts.) (Most likely happens at first boot.)
    ## If Tor has been enabled, restart whonixcheck daemon so whonixcheck will
    ## check Tor's bootstrap status among other things.
    if ! grep "^#DisableNetwork 0$" /etc/tor/torrc ; then
        ## Check if whonixcheck daemon is even running before attempting to
        ## restart it. This aids systems where whonixcheck is not installed.
        if sudo service whonixcheck status ; then
            sudo service whonixcheck restart || true
        fi
    fi

fi
